gate_type: "AND"
inputs:
  intersection:
    topic: "open_loop_intersection_control_node/intersection_done"
  in_lane:
    topic: "lane_filter_node/in_lane"
output_topic: "~intersection_done_and_in_lane"
