LED_protocol:
  # The three frequencies
  freq1: &f1 2.8
  freq2: &f2 4.1 
  freq3: &f3 5.0

  # Color and frequencies aof all signaling states
  CAR_SIGNAL_A:
    frequency_idx: *f1
    color: 'green'

  CAR_SIGNAL_B:
    frequency_idx: *f2
    color: 'purple'

  CAR_SIGNAL_C:
    frequency_idx: *f3
    color: 'yelllow'

  off:
    frequency_idx: *f3
    color: 'black'

  traffic_light_go:
    frequency_idx: *f1
    color: 'green'

  traffic_light_stop:
    frequency_idx: *f2
    color: 'red'
